forcing_variables: !!python/tuple
- year_progress_sin
- year_progress_cos
- day_progress_sin
- day_progress_cos
input_duration: 24h
input_variables: !!python/tuple
- 2m_temperature
- mean_sea_level_pressure
- 10m_v_component_of_wind
- 10m_u_component_of_wind
- sea_surface_temperature
- temperature
- geopotential
- u_component_of_wind
- v_component_of_wind
- vertical_velocity
- specific_humidity
- year_progress_sin
- year_progress_cos
- day_progress_sin
- day_progress_cos
- geopotential_at_surface
- land_sea_mask
pressure_levels: !!python/tuple
- 50
- 100
- 150
- 200
- 250
- 300
- 400
- 500
- 600
- 700
- 850
- 925
- 1000
target_variables: !!python/tuple
- 2m_temperature
- mean_sea_level_pressure
- 10m_v_component_of_wind
- 10m_u_component_of_wind
- total_precipitation_12hr
- sea_surface_temperature
- temperature
- geopotential
- u_component_of_wind
- v_component_of_wind
- vertical_velocity
- specific_humidity
