name: gencast-py312
channels:
  - defaults
dependencies:
  - lz4-c=1.9.4
  - ca-certificates=2025.7.14
  - libnetcdf=4.9.2
  - xorg-libxfixes=6.0.1
  - libexpat=2.7.0
  - libgfortran5=13.2.0
  - expat=2.7.0
  - zlib=1.3.1
  - libxcb=1.17.0
  - _openmp_mutex=5.1
  - libtiff=4.5.0
  - libcblas=3.9.0
  - libuuid=2.38.1
  - proj=9.3.1
  - libedit=3.1.20230828
  - setuptools=78.1.1
  - libgcc-ng=15.1.0
  - libffi=3.4.4
  - xorg-xorgproto=2024.1
  - libcurl=8.4.0
  - bzip2=1.0.8
  - jpeg=9e
  - libsqlite=3.45.2
  - libdeflate=1.17
  - blosc=1.21.6
  - libpng=1.6.50
  - packaging=25.0
  - xorg-libxext=1.3.6
  - libev=4.33
  - pygrib=2.1.6
  - libgomp=15.1.0
  - xorg-libxi=1.8.2
  - libstdcxx=15.1.0
  - libglu=9.0.0
  - _libgcc_mutex=0.1
  - certifi=2025.7.14
  - libxcrypt=4.4.36
  - pthread-stubs=0.3
  - libiconv=1.18
  - xz=5.6.4
  - ld_impl_linux-64=2.40
  - pip=25.1
  - libgcc=15.1.0
  - ncurses=6.4
  - libzip=1.11.2
  - jasper=4.2.4
  - python=3.12.2
  - python_abi=3.12
  - libwebp-base=1.6.0
  - hdf4=4.2.15
  - libaec=1.0.6
  - pycparser=2.22
  - libblas=3.9.0
  - lerc=4.0.0
  - krb5=1.21.3
  - xorg-libxdmcp=1.1.5
  - libssh2=1.11.1
  - xorg-libxau=1.0.12
  - readline=8.2
  - libxml2=2.13.5
  - libgfortran-ng=13.2.0
  - cffi=1.17.1
  - tk=8.6.13
  - hdf5=1.14.2
  - snappy=1.2.1
  - sqlite=3.45.2
  - libnsl=2.0.1
  - eccodes=2.31.0
  - libopenblas=0.3.29
  - zstd=1.5.7
  - xorg-libx11=1.8.12
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - openssl=3.5.1
  - libzlib=1.3.1
  - freeglut=3.4.0
  - c-ares=1.19.1
  - libstdcxx-ng=15.1.0
  - wheel=0.45.1
